"""
https://docs.python.org/3.6/tutorial/errors
https://docs.python.org/3/library/exceptions.html

https://d3c33hcgiwev3.cloudfront.net/_7f3d9452c4b2e62cf901fcbfccb8372a_3.2.2-class_inheritance_export.slides.html?Expires=1533427200&Signature=FKS8uVV-bUsQw-bOQqo5BBtgvtRfWojwhB9VfbozG6huPVfHUI8MWqKgniBMg37HHeF42GOXgPF4yWRzF2ogTxSYPI2DCEBJ4MMWTwxsr2ctZrrkfoPooRpmwawn3pOUaZIim-mz8t9OZ1v~2hfLSC1QBiTFNe55RniwQMNxWzI_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A
https://d3c33hcgiwev3.cloudfront.net/_7dd426404422c8625563b4787d059995_3.1-exceptions_export.slides.html?Expires=1533427200&Signature=NZ8oB~7RicWdsGIWjfXXkwi5pOlmJ9LocDHb43eEj5RbtB98pjoDsEoboyNMTJC~RFLT3LTALjof9qXmzmIGGxf9SCEjZPYpF8r8zhl3JYAuqzROks74owGknclOMo27FJuHFheDmEAq1kyIchRqpIIFZSur7fgOCUv9is7FKlc_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A
"""

# while True:
#     try:
#         x = int(input("Please enter a number:"))
#         break
#     except ValueError:
#         print("Oops! That was no valid number. Try again...")

#=============================================================================================
import sys







